version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Australia/Brisbane'
      WEBPASSWORD: '#YourStrongPassword!'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1'
      TEMPERATUREUNIT: c
      QUERY_LOGGING: "true"
      INTERFACE: "wg0"
      DNSMASQ_LISTENING: local
      DNSSEC: "true"
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: "host"